#
# This file is part of the brauser gem. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#
 
Brauser::Definitions.register(:language, "af", "Afrikaans")
Brauser::Definitions.register(:language, "sq", "Albanian")
Brauser::Definitions.register(:language, "eu", "Basque")
Brauser::Definitions.register(:language, "bg", "Bulgarian")
Brauser::Definitions.register(:language, "be", "Byelorussian")
Brauser::Definitions.register(:language, "ca", "Catalan")
Brauser::Definitions.register(:language, "zh", "Chinese")
Brauser::Definitions.register(:language, "zh-cn", "Chinese/China")
Brauser::Definitions.register(:language, "zh-tw", "Chinese/Taiwan")
Brauser::Definitions.register(:language, "zh-hk", "Chinese/Hong Kong")
Brauser::Definitions.register(:language, "zh-sg", "Chinese/singapore")
Brauser::Definitions.register(:language, "hr", "Croatian")
Brauser::Definitions.register(:language, "cs", "Czech")
Brauser::Definitions.register(:language, "da", "Danish")
Brauser::Definitions.register(:language, "nl", "Dutch")
Brauser::Definitions.register(:language, "nl-nl", "Dutch/Netherlands")
Brauser::Definitions.register(:language, "nl-be", "Dutch/Belgium")
Brauser::Definitions.register(:language, "en", "English")
Brauser::Definitions.register(:language, "en-gb", "English/United Kingdom")
Brauser::Definitions.register(:language, "en-us", "English/United States")
Brauser::Definitions.register(:language, "en-au", "English/Australian")
Brauser::Definitions.register(:language, "en-ca", "English/Canada")
Brauser::Definitions.register(:language, "en-nz", "English/New Zealand")
Brauser::Definitions.register(:language, "en-ie", "English/Ireland")
Brauser::Definitions.register(:language, "en-za", "English/South Africa")
Brauser::Definitions.register(:language, "en-jm", "English/Jamaica")
Brauser::Definitions.register(:language, "en-bz", "English/Belize")
Brauser::Definitions.register(:language, "en-tt", "English/Trinidad")
Brauser::Definitions.register(:language, "et", "Estonian")
Brauser::Definitions.register(:language, "fo", "Faeroese")
Brauser::Definitions.register(:language, "fa", "Farsi")
Brauser::Definitions.register(:language, "fi", "Finnish")
Brauser::Definitions.register(:language, "fr", "French")
Brauser::Definitions.register(:language, "fr-be", "French/Belgium")
Brauser::Definitions.register(:language, "fr-fr", "French/France")
Brauser::Definitions.register(:language, "fr-ch", "French/Switzerland")
Brauser::Definitions.register(:language, "fr-ca", "French/Canada")
Brauser::Definitions.register(:language, "fr-lu", "French/Luxembourg")
Brauser::Definitions.register(:language, "gd", "Gaelic")
Brauser::Definitions.register(:language, "gl", "Galician")
Brauser::Definitions.register(:language, "de", "German")
Brauser::Definitions.register(:language, "de-at", "German/Austria")
Brauser::Definitions.register(:language, "de-de", "German/Germany")
Brauser::Definitions.register(:language, "de-ch", "German/Switzerland")
Brauser::Definitions.register(:language, "de-lu", "German/Luxembourg")
Brauser::Definitions.register(:language, "de-li", "German/Liechtenstein")
Brauser::Definitions.register(:language, "el", "Greek")
Brauser::Definitions.register(:language, "he", "Hebrew")
Brauser::Definitions.register(:language, "he-il", "Hebrew/Israel")
Brauser::Definitions.register(:language, "hi", "Hindi")
Brauser::Definitions.register(:language, "hu", "Hungarian")
Brauser::Definitions.register(:language, "ie-ee", "Internet Explorer/Easter Egg")
Brauser::Definitions.register(:language, "is", "Icelandic")
Brauser::Definitions.register(:language, "id", "Indonesian")
Brauser::Definitions.register(:language, "in", "Indonesian")
Brauser::Definitions.register(:language, "ga", "Irish")
Brauser::Definitions.register(:language, "it", "Italian")
Brauser::Definitions.register(:language, "it-ch", "Italian/ Switzerland")
Brauser::Definitions.register(:language, "ja", "Japanese")
Brauser::Definitions.register(:language, "km", "Khmer")
Brauser::Definitions.register(:language, "km-kh", "Khmer/Cambodia")
Brauser::Definitions.register(:language, "ko", "Korean")
Brauser::Definitions.register(:language, "lv", "Latvian")
Brauser::Definitions.register(:language, "lt", "Lithuanian")
Brauser::Definitions.register(:language, "mk", "Macedonian")
Brauser::Definitions.register(:language, "ms", "Malaysian")
Brauser::Definitions.register(:language, "mt", "Maltese")
Brauser::Definitions.register(:language, "no", "Norwegian")
Brauser::Definitions.register(:language, "pl", "Polish")
Brauser::Definitions.register(:language, "pt", "Portuguese")
Brauser::Definitions.register(:language, "pt-br", "Portuguese/Brazil")
Brauser::Definitions.register(:language, "rm", "Rhaeto-Romanic")
Brauser::Definitions.register(:language, "ro", "Romanian")
Brauser::Definitions.register(:language, "ro-mo", "Romanian/Moldavia")
Brauser::Definitions.register(:language, "ru", "Russian")
Brauser::Definitions.register(:language, "ru-mo", "Russian /Moldavia")
Brauser::Definitions.register(:language, "sr", "Serbian")
Brauser::Definitions.register(:language, "sk", "Slovack")
Brauser::Definitions.register(:language, "sl", "Slovenian")
Brauser::Definitions.register(:language, "sb", "Sorbian")
Brauser::Definitions.register(:language, "es", "Spanish")
Brauser::Definitions.register(:language, "es-do", "Spanish")
Brauser::Definitions.register(:language, "es-ar", "Spanish/Argentina")
Brauser::Definitions.register(:language, "es-co", "Spanish/Colombia")
Brauser::Definitions.register(:language, "es-mx", "Spanish/Mexico")
Brauser::Definitions.register(:language, "es-es", "Spanish/Spain")
Brauser::Definitions.register(:language, "es-gt", "Spanish/Guatemala")
Brauser::Definitions.register(:language, "es-cr", "Spanish/Costa Rica")
Brauser::Definitions.register(:language, "es-pa", "Spanish/Panama")
Brauser::Definitions.register(:language, "es-ve", "Spanish/Venezuela")
Brauser::Definitions.register(:language, "es-pe", "Spanish/Peru")
Brauser::Definitions.register(:language, "es-ec", "Spanish/Ecuador")
Brauser::Definitions.register(:language, "es-cl", "Spanish/Chile")
Brauser::Definitions.register(:language, "es-uy", "Spanish/Uruguay")
Brauser::Definitions.register(:language, "es-py", "Spanish/Paraguay")
Brauser::Definitions.register(:language, "es-bo", "Spanish/Bolivia")
Brauser::Definitions.register(:language, "es-sv", "Spanish/El salvador")
Brauser::Definitions.register(:language, "es-hn", "Spanish/Honduras")
Brauser::Definitions.register(:language, "es-ni", "Spanish/Nicaragua")
Brauser::Definitions.register(:language, "es-pr", "Spanish/Puerto Rico")
Brauser::Definitions.register(:language, "sx", "Sutu")
Brauser::Definitions.register(:language, "sv", "Swedish")
Brauser::Definitions.register(:language, "sv-se", "Swedish/Sweden")
Brauser::Definitions.register(:language, "sv-fi", "Swedish/Finland")
Brauser::Definitions.register(:language, "ts", "Thai")
Brauser::Definitions.register(:language, "tn", "Tswana")
Brauser::Definitions.register(:language, "tr", "Turkish")
Brauser::Definitions.register(:language, "uk", "Ukrainian")
Brauser::Definitions.register(:language, "ur", "Urdu")
Brauser::Definitions.register(:language, "vi", "Vietnamese")
Brauser::Definitions.register(:language, "xh", "Xshosa")
Brauser::Definitions.register(:language, "ji", "Yiddish")
Brauser::Definitions.register(:language, "zu", "Zulu")